/*!
 * Copyright (c) Microsoft. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project.
 */
/* eslint-disable @typescript-eslint/no-var-requires */
import * as fs from 'fs'
import * as path from 'path'
import { readCsvFile } from '../readCsvFile'
import {
	Link,
	Qualification,
	Region,
	RolloutPhase,
} from '@ms-covidbot/state-plan-schema'

const REPO_TOP = path.join(__dirname, '../../../../')
const DIST_DIR = path.join(__dirname, '../../dist')
const OUTPUT_FILE = path.join(REPO_TOP, 'DATA_REVIEW.md')
const STATES_DATA_JSON = path.join(DIST_DIR, 'states.json')
const LOCALIZATION_CSV = path.join(DIST_DIR, 'localization.csv')

type LocalizationRecord = Record<string, string>
type LocalizationMap = Map<string, LocalizationRecord>

function generateReviewDocument(): void {
	console.log('Generating Review Document...')
	const statesData = require(STATES_DATA_JSON)
	const csvData: LocalizationRecord[] = []
	readCsvFile(LOCALIZATION_CSV, csvData)

	const localizations: LocalizationMap = new Map()
	csvData.forEach((datum) => {
		localizations.set(datum['String ID'], datum)
	})

	const result = `
${writeAutoGeneratedHeader()}
${statesData
	.map((state: Region) => writeStateInfo(state, localizations))
	.join('\n\n\n\n')}
	
${writeNonEligibilityTable(csvData.filter((r) => !isEligibilityRecord(r)))}
	`

	fs.writeFileSync(OUTPUT_FILE, result, { encoding: 'utf8' })
}

function isEligibilityRecord(record: LocalizationRecord): boolean {
	return record['String ID'].startsWith('c19.eligibility')
}

function writeNonEligibilityTable(records: LocalizationRecord[]): string {
	return `# Non-Eligibility Localizations (strings used in the Bot flow):
${writeLocalizationHeader()}
${records.map((r) => writeLocalizationRecord(r)).join('\n')}
`
}

/**
 * Writes out state information
 * @param state The state to write out
 * @param localizations localization strings by key
 */
function writeStateInfo(state: Region, localizations: LocalizationMap): string {
	const subregionInfo =
		(state.regions || []).length > 0
			? '\n\n' +
			  state.regions
					?.map((region) => writeRegionInfo(region, localizations, state))
					.join('\n')
			: ''

	return `
${writeRegionInfo(state, localizations)}
${subregionInfo}
`
}

function writeRegionInfo(
	region: Region,
	localizations: LocalizationMap,
	parent?: Region | undefined
): string {
	const activePhase = getActivePhase(region, parent)
	const phaseLabel = getPhaseLabel(activePhase)
	const writeOutPhases =
		region.type === 'state' || (region.plan?.phases || []).length > 0
	const phasesToWrite = region.plan?.phases || []

	const phaseData = writeOutPhases
		? `## Phases
${phasesToWrite
	.map((phase) => writePhaseInfo(phase, localizations, phase === activePhase))
	.join('\n')}
`
		: ''

	const infoLink = region.plan?.links?.info
		? `- Info Link: **${writeLink(region.plan?.links?.info, localizations)}**\n`
		: ''
	const workflowLink = region.plan?.links?.workflow
		? `- Workflow Link: **${writeLink(
				region.plan?.links?.workflow,
				localizations
		  )}**\n`
		: ''
	const schedulingLink = region.plan?.links?.scheduling
		? `- Scheduling Link: **${writeLink(
				region.plan?.links?.scheduling,
				localizations
		  )}**\n`
		: ''
	const registrationLink = region.plan?.links?.registration
		? `- Registration Link: **${writeLink(
				region.plan?.links?.registration,
				localizations
		  )}**\n`
		: ''
	const providersLink = region.plan?.links?.providers
		? `- Providers Link: **${writeLink(
				region.plan?.links?.providers,
				localizations
		  )}**\n`
		: ''
	const hotlineLink = region.plan?.links?.scheduling_phone
		? `- Scheduling Hotline: **${writeLink(
				region.plan?.links?.scheduling_phone,
				localizations
		  )}**\n`
		: ''

	return `
# ${region.name} (${region.type})
- Active Phase: **${phaseLabel}**\n
${infoLink}${workflowLink}${hotlineLink}${schedulingLink}${registrationLink}${providersLink}
${phaseData}
`
}

function writeLink(
	link: Link | undefined,
	localizations: LocalizationMap
): string | undefined {
	if (link != null) {
		const textLoc = localizations.get(link.text)
		const descriptionLoc = link.description
			? localizations.get(link.description)
			: undefined

		if (!textLoc) {
			throw new Error('could not find text for link' + link.text)
		}
		const text = textLoc['en-us']
		const description = (descriptionLoc && descriptionLoc['en-us']) || undefined
		return `[${text}](${link.url})${
			description != null ? ' description=' + description : ''
		}`
	}
}

function getActivePhase(
	state: Region,
	parent: Region | undefined
): RolloutPhase {
	const phaseId =
		state.plan?.activePhase || parent?.plan?.activePhase || 'NO PHASE SPECIFIED'
	const allPhases = [
		...(parent?.plan?.phases || []),
		...(state.plan?.phases || []),
	]
	const phase = allPhases.find((phase) => {
		return phase.id === phaseId
	})
	if (phase == null) {
		throw new Error(`Could not find ${phaseId} in ${state.name}`)
	}
	return phase
}

function writePhaseInfo(
	phase: RolloutPhase,
	localizations: LocalizationMap,
	isActive: boolean
): string {
	function writeQualificationRow(row: Qualification): string {
		const questionLoc = localizations.get(row.question)
		const moreInfoLoc: LocalizationRecord | undefined = row.moreInfoText
			? localizations.get(row.moreInfoText)
			: undefined
		if (questionLoc == null) {
			throw new Error(`could not find string with id ${row.question}`)
		}
		return (
			writeLocalizationRecord(questionLoc, 'n/a') +
			(moreInfoLoc
				? '\n' + writeLocalizationRecord(moreInfoLoc, row.moreInfoUrl || 'none')
				: '')
		)
	}

	return `### *${getPhaseLabel(phase)}* ${
		isActive ? '**(CURRENTLY ACTIVE)**' : ''
	}
${writeLocalizationHeader()}
${phase.qualifications.map(writeQualificationRow).join('\n')} 
`
}

function getPhaseLabel(phase: RolloutPhase): string {
	return phase.label ? phase.label : `Phase ${phase.id.toUpperCase()}`
}

function writeLocalizationHeader(): string {
	return `| id | en-us | es-us | zh-cn | ko-kr | vi-vn | other info |
| --- | --- | --- | --- | --- | --- | --- |`
}
function writeLocalizationRecord(
	loc: LocalizationRecord,
	moreInfo = 'none'
): string {
	return (
		'|' +
		[
			loc['String ID'],
			loc['en-us'] || 'not defined',
			loc['es-us'] || 'not defined',
			loc['zh-cn'] || 'not defined',
			loc['ko-kr'] || 'not defined',
			loc['vi-vn'] || 'not defined',
			moreInfo,
		].join('|')
	)
}

function writeAutoGeneratedHeader(): string {
	return `<!-- 
	THIS FILE IS AUTO-GENERATED, DO NOT EDIT. 
	Plans and Localizations can be edited in the packages/plans folder
-->`
}

generateReviewDocument()
