# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: covid-healthbot-container
  AZURE_WEBAPP_NAME_API: ms-covid-vaxbot-api
  NODE_VERSION: '12.x'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install yarn
        run: npm i -g yarn

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install dependencies
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: verify packages
        run: yarn ci

      - name: Deploy Resources to Dev HealthBot
        run: yarn deploy:data
        if: github.ref == 'refs/heads/main'
        env:
          HEALTHBOT_HOST: ${{ secrets.HEALTHBOT_HOST }}
          HEALTHBOT_TENANT: 'covid-healthbot-dev-d8jgdjs'
          HEALTHBOT_API_SECRET: ${{ secrets.HEALTHBOT_API_KEY_DEV }}

      - name: Deploy Resources to Integ HealthBot
        run: yarn deploy:data
        if: github.ref == 'refs/heads/main'
        env:
          HEALTHBOT_HOST: ${{ secrets.HEALTHBOT_HOST }}
          HEALTHBOT_TENANT: 'covid-healthbot-integ-fvwiurf'
          HEALTHBOT_API_SECRET: ${{ secrets.HEALTHBOT_API_KEY_INTEG }}

      - name: Deploy Resources to Production HealthBot (MITRE)
        run: yarn deploy:data
        if: github.ref == 'refs/heads/main'
        env:
          HEALTHBOT_HOST: ${{ secrets.HEALTHBOT_HOST }}
          HEALTHBOT_TENANT: 'tfiiu-vaccine-cmhp8hl'
          HEALTHBOT_API_SECRET: ${{ secrets.HEALTHBOT_API_KEY_INTEG }}

      - name: Install Bot Container Deployment Modules
        if: github.ref == 'refs/heads/main'
        run: pushd packages/healthbotapp/dist && npm install && popd

      - name: 'Deploy Bot Container to Azure WebApp'
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: packages/healthbotapp/dist

      - name: Install API Deployment Modules
        if: github.ref == 'refs/heads/main'
        run: pushd packages/api/dist && npm install && popd

      - name: 'Deploy API to Azure WebApp'
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_API }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: packages/api/dist
